title: "Macarena Gárate"
description: "Portfolio made in 'cvless' Jekyll theme for a beautiful online CV"
baseurl: ""
url: "https://mgaratem.github.io/"

theme: minima

# site settings
taglong: Ssr. Backend Developer
tagshort: Backend Developer

# social media links
social:
  github: mgaratem
  linkedin: mgaratem
  stackoverflow: 135801/mgarate

# author settings
author:
  name: Macarena Gárate
  email: mgaratemu@gmail.com
address: Quilpué, Chile
phone: +56 9 74519090

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md

parallel_localization: false