title: "Macarena Gárate"
description: "Portfolio made in 'cvless' Jekyll theme for a beautiful online CV"
baseurl: ""
url: "https://mgaratem.github.io/"

theme: minima

# site settings
taglong: Ssr. Backend Developer
tagshort: Backend Developer

# social media links
social:
  github: mgaratem
  linkedin: mgaratem
  stackoverflow: 135801/mgarate

# author settings
author:
  name: Macarena Gárate
  email: mgaratemu@gmail.com
address: Quilpué, Chile
phone: (+569) 74519090

photo: assets/files/techno.png

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sass_dir: _sass           # Directorio donde se encuentran los archivos SCSS
  style: compressed         # Estilo del CSS generado: compressed, nested, expanded, etc.
  sourcemap: never           # Configura la generación de mapas de origen: never, auto, always

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md

parallel_localization: false